name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Unzip assets
        run: unzip -o assets.zip -d public/

      - name: Delete ZIP file (اختياري)
        run: rm -f assets.zip || echo "No ZIP file to delete"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
